export const categories = [
    {
        title: "Assistindo",
        items: [
            {
                img: "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg", top10: true, badge: "Clássico", badgeColor: "red", progress: 0,
                youtube: "https://www.youtube.com/watch?v=bLvqoHBptjg"
            },
            {
                img: "https://aventurasnahistoria.com.br/wp-content/uploads/entretenimento/gladiador_2_VvnGVes.jpg", progress: 0,
                youtube: "https://www.youtube.com/watch?v=cXg62-t8BWs"
            },
            {
                img: "https://i.ytimg.com/vi/OQgySPQ5M3Y/maxresdefault.jpg", progress: 0,
                youtube: "https://www.youtube.com/watch?v=zckJCxYxn1g"
            },
            {
                img: "https://ingresso-a.akamaihd.net/img/cinema/cartaz/14413-destaque.jpg", progress: 0,
                youtube: "https://www.youtube.com/watch?v=a06zxOyQrAs"
            },
        ]
    },
    {
        title: "Séries",
        items: [
            { img: "https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?q=80&w=600&auto=format&fit=crop", top10: true, badge: "Nova temporada", badgeColor: "red", youtube: "https://www.youtube.com/watch?v=wLo9bfgla4k" },
            { img: "https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?q=80&w=600&auto=format&fit=crop", top10: true, youtube: "https://www.youtube.com/watch?v=wLo9bfgla4k" },
            { img: "https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?q=80&w=600&auto=format&fit=crop", badge: "Novo episódio", badgeColor: "red", youtube: "https://www.youtube.com/watch?v=wLo9bfgla4k" },
            { img: "https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?q=80&w=600&auto=format&fit=crop", badge: "Novidade", badgeColor: "red", youtube: "https://www.youtube.com/watch?v=wLo9bfgla4k" },
        ]
    },
    {
        title: "Filmes",
        items: [
            { img: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?q=80&w=600&auto=format&fit=crop", top10: true, youtube: "https://www.youtube.com/watch?v=wLo9bfgla4k" },
            { img: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?q=80&w=600&auto=format&fit=crop", top10: true, badge: "Novidade", badgeColor: "red", youtube: "https://www.youtube.com/watch?v=wLo9bfgla4k" },
            { img: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?q=80&w=600&auto=format&fit=crop", top10: true, badge: "Novo episódio", badgeColor: "red", youtube: "https://www.youtube.com/watch?v=wLo9bfgla4k" },
            { img: "https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?q=80&w=600&auto=format&fit=crop", top10: true, badge: "Novo episódio", badgeColor: "red", youtube: "https://www.youtube.com/watch?v=wLo9bfgla4k" },
        ]
    }
];

export const profileCategoryItems = {
    Rowena: {
        "Assistindo": [
            { img: "https://image.tmdb.org/t/p/original/qL6jeOLSSn4BwM6hCUWR5Hj5qcr.jpg", 
                top10: true, 
                badge: "Clássico", 
                badgeColor: "red", 
                progress: 80,
                youtube: "https://www.youtube.com/watch?v=1dYv5u6v55Y" ,
                relevancia: 90,
                idade: "L",
                duracao: "2h08",    
                tags: ["Romance", "Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/x7n68dlDNwS8TjuqKme4gbBbiH4.jpg", 
                progress: 80,
                youtube: "https://www.youtube.com/watch?v=5ZAhzsi1ybM" ,
                relevancia: 95,
                idade: "A18",
                duracao: "2h34",    
                tags: ["Crime", "Thriller"]
            },
            { img: "https://image.tmdb.org/t/p/original/A1x46Y1hSIrklz440AiYWQkjbHX.jpg", 
                progress: 18,
                youtube: "https://www.youtube.com/watch?v=_NzqP0jmk3o" ,
                relevancia: 89,
                idade: "A14",
                duracao: "2h15",    
                tags: ["Drama", "História"]
            },
            { img: "https://image.tmdb.org/t/p/original/cQDfBNvj2PVUIve47PcsrcbYNXt.jpg", 
                progress: 63,
                youtube: "https://www.youtube.com/watch?v=sBCE9oIuN24" ,
                relevancia: 90,
                idade: "A12",
                duracao: "6 temporadas",    
                tags: ["Comédia"]
            },
        ],
        "Séries": [
            { img: "https://image.tmdb.org/t/p/original/l33rXuCIQnrupXC4YneYaLpgLvt.jpg", 
                top10: true, 
                badge: "Nova temporada", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=nn2Q69pSC_M" ,
                relevancia: 94,
                idade: "A14",
                duracao: "7 temporadas",    
                tags: ["Crime", "Drama", "Mistério"]
            },
            { img: "https://image.tmdb.org/t/p/original/v06vhrjmMAaYtMmhs6F0GuSIBq6.jpg", 
                top10: true, 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=KKziOmsJxzE" ,
                relevancia: 94,
                idade: "A16",
                duracao: "11 temporadas",    
                tags: ["Mistério", "Crime", "Ficção científica"]
            },
            { img: "https://image.tmdb.org/t/p/original/89T83vE1ol8wcI879LutCqv7hMa.jpg", 
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 40,
                youtube: "https://www.youtube.com/watch?v=b9EkMc79ZSU" ,
                relevancia: 96,
                idade: "A16",
                duracao: "5 temporadas",    
                tags: ["Ficção científica", "Fantasia", "Mistério"]
            },
            { img: "https://image.tmdb.org/t/p/original/fT4j8UthvOV93Xb9BiZ3wLrOJth.jpg", 
                badge: "Novidade", 
                badgeColor: "red", 
                progress: 85,
                youtube: "https://www.youtube.com/watch?v=JWtnJjn6ng0" ,
                relevancia: 92,
                idade: "A14",
                duracao: "6 temporadas",    
                tags: ["Drama"]
            },
        ],
        "Filmes": [
            { img: "https://image.tmdb.org/t/p/original/8TJF697vsJDy3ShuoapqGCfBJBN.jpg", 
                top10: true, 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=_mHgGU4AbOA" ,
                relevancia: 90,
                idade: "L",
                duracao: "2h13",    
                tags: ["Romance", "Musical", "Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/ldFX26JW3fusyMewRoWoXYWaffw.jpg", 
                top10: true, 
                badge: "Novidade", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=pBk4NYhWNMM" ,
                relevancia: 79,
                idade: "A12",
                duracao: "1h54",    
                tags: ["Comédia", "Aventura"]
            },
            { img: "https://image.tmdb.org/t/p/original/hOOWBR8GaN1XlI4GHooFG22IQ1U.jpg",
                top10: true, 
                badgeColor: "red", 
                progress: 50,
                youtube: "https://www.youtube.com/watch?v=6MUcuqbGTxc",
                relevancia: 90,
                idade: "A12",
                duracao: "1h40",    
                tags: ["Drama", "Romance"]
            },
            { img: "https://image.tmdb.org/t/p/original/25B9lbnt4nnlj3hPf5nr77Q5p2B.jpg", 
                top10: true, 
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=7kSuas6mRpk" ,
                relevancia: 90,
                idade: "A18",
                duracao: "2h51",    
                tags: ["Ação", "Crime"]
            },
        ]
    },
    Leo: {
        "Assistindo": [
            { img: "https://image.tmdb.org/t/p/original/qhWq6FviYLVNeO8l4ZT1BzdDb2t.jpg", 
                top10: true, 
                badge: "Ação", 
                badgeColor: "red", 
                progress: 22,
                youtube: "https://www.youtube.com/watch?v=U0LETmDvuXc" ,
                relevancia: 84,
                idade: "A14",
                duracao: "1h52",    
                tags: ["Terror", "Mistério", "Crime"]
            },
            { img: "https://image.tmdb.org/t/p/original/vUr8PiaJugDhMquPxjNdHp6tshr.jpg", 
                progress: 95,
                youtube: "https://www.youtube.com/watch?v=qvsgGtivCgs" ,
                relevancia: 93,
                idade: "L",
                duracao: "1h55",    
                tags: ["Aventura","Comédia", "Ficção científica"]
            },
            { img: "https://image.tmdb.org/t/p/original/otCnAN1edreRudT5E2OHk8beiDu.jpg", 
                progress: 32,
                youtube: "https://www.youtube.com/watch?v=_-Nv0JOcGxg" ,
                relevancia: 99,
                idade: "A16",
                duracao: "5 temporadas",    
                tags: ["Drama", "Crime"]
            },
            { img: "https://image.tmdb.org/t/p/original/3le0XaQSMvzW8bAnUWPSvn5K7ci.jpg", 
                progress: 80,
                youtube: "https://www.youtube.com/watch?v=cu2ApTImBKc" ,
                relevancia: 91,
                idade: "A16",
                duracao: "11 temporadas",    
                tags: ["Action", "Adventure", "Drama"]
            },
        ],
        "Séries": [
            { img: "https://image.tmdb.org/t/p/original/508LZMERHPfU6KQcIKmyz5QqxMZ.jpg", 
                top10: true, 
                badge: "Suspense", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=jBfOlQrko0c" ,
                relevancia: 90,
                idade: "A18",
                duracao: "4 temporadas",    
                tags: ["Ficção científica","Faroeste", "Fantasia"]
            },
            { img: "https://image.tmdb.org/t/p/original/v62W95eWzTXFymd7UliUSMGfvA4.jpg", 
                top10: true, 
                progress: 74,
                youtube: "https://www.youtube.com/watch?v=KPLWWIOCOOQ" ,
                relevancia: 95,
                idade: "A16",
                duracao: "8 temporadas",    
                tags: ["Ficção científica", "Drama", "Fantasia"]
            },
            { img: "https://image.tmdb.org/t/p/original/hwq0LPIG1hreKvS6IKFaLk8UF0.jpg", 
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=B1OL4ZQf70c" ,
                relevancia: 92,
                idade: "A14",
                duracao: "9 temporadas",    
                tags: ["Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/5auRDbia1UZAYtVYAJmZ8oGatd0.jpg", 
                badge: "Novidade", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=J4LWdJHJxbs" ,
                relevancia: 92,
                idade: "A18",
                duracao: "2 temporadas",    
                tags: ["Drama", "Crime"]
            },
        ],
        "Filmes": [
            { img: "https://image.tmdb.org/t/p/original/18vIqvqmsOhtIGVGWhTafLM0uAE.jpg", 
                top10: true, 
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=DlM2CWNTQ84" ,
                relevancia: 75,
                idade: "A12",
                duracao: "2h21",    
                tags: ["Ação", "Aventura", "Ficção científica"]
            },
            { img: "https://image.tmdb.org/t/p/original/lHTxDYso04WyDo5x4Vzxgi9EHJN.jpg", 
                top10: true, 
                badge: "Novidade", 
                badgeColor: "red", 
                progress: 56,
                youtube: "https://www.youtube.com/watch?v=iTgk3WbTErk" ,
                relevancia: 94,
                idade: "A12",
                duracao: "1h47",    
                tags: ["Drama", "Música", "Thriller"]
            },
            { img: "https://image.tmdb.org/t/p/original/oMCUPlwnk2z3QDnzXBxYY6hJogQ.jpg", 
                top10: true, 
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 68,
                youtube: "https://www.youtube.com/watch?v=vKQi3bBA1y8" ,
                relevancia: 92,
                idade: "A12",
                duracao: "2h16",    
                tags: ["Ação", "Ficção científica"]
            },
            { img: "https://image.tmdb.org/t/p/original/jbO3nkohyvxK39DYy1HgejSzftx.jpg", 
                top10: true, 
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=bKGxHflevuk" ,
                relevancia: 85,
                idade: "A16",
                duracao: "2h18",    
                tags: ["Terror", "Ação", "Thriller"]
            },
        ]
    },
    Vee: {
        "Assistindo": [
            { img: "https://image.tmdb.org/t/p/original/a5DqjlKF6gn1V83AuPNUyRov20D.jpg", 
                top10: true, 
                badge: "Comédia", 
                badgeColor: "red", 
                progress: 12,
                youtube: "https://www.youtube.com/watch?v=_u6vYpbfCmQ" ,
                relevancia: 89,
                idade: "A10",
                duracao: "6 temporadas",    
                tags: ["Sitcom", "Família"]
            },
            { img: "https://image.tmdb.org/t/p/original/kSb1sF7pAWmZJY2vjP97hnfwVkF.jpg", 
                progress: 78,
                youtube: "https://www.youtube.com/watch?v=IqaXNwAzSmQ" ,
                relevancia: 91,
                idade: "A16",
                duracao: "4 temporadas",    
                tags: ["Romance", "Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/iWc6rzyWeUgW61JZNgIxBLD3nsG.jpg", 
                progress: 32,
                youtube: "https://www.youtube.com/watch?v=-G9BqkgZXRA" ,
                relevancia: 94,
                idade: "A10",
                duracao: "4 temporadas",    
                tags: ["Aventura", "Animação", "Action"]
            },
            { img: "https://image.tmdb.org/t/p/original/lsZCeynGhauXhejI0bWCeUHvR0F.jpg", 
                progress: 87,
                youtube: "https://www.youtube.com/watch?v=5UnjrG_N8hU" ,
                relevancia: 85,
                idade: "A10",
                duracao: "2h20",    
                tags: ["Ação", "Ficção científica", "Aventura"]
            },
        ],
        "Séries": [
            { img: "https://image.tmdb.org/t/p/original/2zjEYhbPKhyMZdLFMh44kXr6MZt.jpg", 
                top10: true, 
                badge: "Infantil", 
                badgeColor: "red", 
                progress: 99,
                youtube: "https://www.youtube.com/watch?v=_pa1KLXuW0Y" ,
                relevancia: 94,
                idade: "A14",
                duracao: "3 temporadas",    
                tags: ["Ação", "Ficção científica", "Fantasia"]
            },
            { img: "https://image.tmdb.org/t/p/original/fNv0sCKQNkOnvSl3OfUFPFrO3Py.jpg", 
                top10: true, 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=Eq3pF5OhlJk" ,
                relevancia: 95,
                idade: "A14",
                duracao: "4 temporadas",    
                tags: ["Mistério", "Crime", "Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/7J5d7K4JBDZ4IDODNX3THLggtM5.jpg", 
                top10: true,
                badge: "Série", 
                badgeColor: "red", 
                progress: 89,
                youtube: "https://www.youtube.com/watch?v=A7TgB4t_6Jw" ,
                relevancia: 92,
                idade: "A14",
                duracao: "22 temporadas",    
                tags: ["Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/nNU9WCkxEfBujzboBmSMOXGdLrT.jpg", 
                badge: "Novidade", 
                badgeColor: "red", 
                progress: 12,
                youtube: "https://www.youtube.com/watch?v=H29XSxoKp80" ,
                relevancia: 94,
                idade: "A12",
                duracao: "10 temporadas",    
                tags: ["Sitcom", "Comédia"]
            },
        ],
        "Filmes": [
            { img: "https://image.tmdb.org/t/p/original/3qKwCdg0H7wxz8JoKKCMHlGidMs.jpg", 
                top10: true, 
                progress: 65,
                youtube: "https://www.youtube.com/watch?v=ycoY201RTRo" ,
                relevancia: 86,
                idade: "L",
                duracao: "1h40",    
                tags: ["Infantil", "Musical", "Animação"]
            },
            { img: "https://image.tmdb.org/t/p/original/ueolTUOXKaOuygKNqUAT7M2evvy.jpg", 
                top10: true, 
                badge: "Novidade", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=6COmYeLsz4c" ,
                relevancia: 79,
                idade: "A10",
                duracao: "2h41",    
                tags: ["Musical", "Romance", "Fantasia"]
            },
            { img: "https://image.tmdb.org/t/p/original/7xot9AxzZWYwlrQN80uUfmLyjKP.jpg", 
                top10: true, 
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=aQXh_AaJXaM" ,
                relevancia: 85,
                idade: "A14",
                duracao: "2h02",    
                tags: ["Drama", "Música"]
            },
            { img: "https://image.tmdb.org/t/p/original/zj2M5916Nqp1apPqCUCvONSbesN.jpg", 
                top10: true, 
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 0,
                youtube: "" ,
                relevancia: 78,
                idade: "A12",
                duracao: "1h43",    
                tags: ["Comédia", "Fantasia", "Terror"]
            },
        ]
    },
    Lola: {
        "Assistindo": [
            { img: "https://image.tmdb.org/t/p/original/yMXRZYGdFa8kcJN9ssl0zrmlhY5.jpg", 
                progress: 18,
                youtube: "https://www.youtube.com/watch?v=Y22NgkErOAk" ,
                relevancia: 97,
                idade: "A16",
                duracao: "2h22",    
                tags: ["Drama", "Crime"]
            },
            { img: "https://image.tmdb.org/t/p/original/1rVD8wbb3O8zC7qjwfenFKiZ88o.jpg", 
                progress: 78, 
                youtube: "https://www.youtube.com/watch?v=-C2z-nshFts" ,
                relevancia: 96,
                idade: "A14",
                duracao: "9 temporadas",    
                tags: ["Comédia"]
            },
            { img: "https://image.tmdb.org/t/p/original/5lJvx8HDUT5UpwkjhvO5VPVApdv.jpg",
                progress: 12,
                youtube: "https://www.youtube.com/watch?v=uxjNDE2fMjI",
                relevancia: 73,
                idade: "A12",
                duracao: "2h02",    
                tags: ["Fantasia","Drama", "Romance"]
            },
            { img: "https://image.tmdb.org/t/p/original/lStohEROE7obb8DmTvtGbC6wELq.jpg", 
                top10: true, 
                badge: "Drama", 
                badgeColor: "red", 
                progress: 30,
                youtube: "https://www.youtube.com/watch?v=-1v_q6TWAL4" ,
                relevancia: 91,
                idade: "A14",
                duracao: "7 temporadas",    
                tags: ["Fantasia", "Ficção cientifíca"]
            },
        ],
        "Séries": [
            { img: "https://image.tmdb.org/t/p/original/tcFm1ytEDMe1FAdqxdsaNihwlez.jpg", 
                top10: true, 
                badge: "Drama", 
                badgeColor: "red", 
                progress: 60,
                youtube: "https://www.youtube.com/watch?v=Nd3Qlo0qspU" ,
                relevancia: 93,
                idade: "A16",
                duracao: "2 temporadas",    
                tags: ["Comédia", "Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/5mJWpKnjAkSWn3g3esFKVt0ALiJ.jpg", 
                top10: true, 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=LcDQqGJG8pA" ,
                relevancia: 92,
                idade: "A14",
                duracao: "10 temporadas",    
                tags: ["Action","Adventure", "Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/mU9CCBZZ24g45koGRoSgUQQMnPs.jpg", 
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 50,
                youtube: "https://www.youtube.com/watch?v=cjJLEYMzpjc" ,
                relevancia: 91,
                idade: "A12",
                duracao: "9 temporadas",    
                tags: ["Comédia"]
            },
            { img: "https://image.tmdb.org/t/p/original/f1oditpv2BaFLO1fWv3E5JzjQGv.jpg", 
                badge: "Novidade", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=6eCoR6vmNzQ" ,
                relevancia: 92,
                idade: "A14",
                duracao: "6 temporadas",    
                tags: ["Drama", "Mistério"]
            },
        ],
        "Filmes": [
            { img: "https://image.tmdb.org/t/p/original/tGppwHNP2bcB9PEreTbZCvNgfBt.jpg", 
                top10: true, 
                progress: 67,
                youtube: "https://www.youtube.com/watch?v=yEmcEuS6xm4" ,
                relevancia: 86,
                idade: "A12",
                duracao: "1h37",    
                tags: ["Comédia", "Romance", "Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/7oBlplQLcQ0E8rF6Pd4Cbi9ADg.jpg", 
                top10: true, 
                badge: "Novidade", 
                badgeColor: "red", 
                progress: 0,
                youtube: "https://www.youtube.com/watch?v=k10ETZ41q5o" ,
                relevancia: 85,
                idade: "A14",
                duracao: "1h52",    
                tags: ["Terror", "Thriller"]
            },
            { img: "https://image.tmdb.org/t/p/original/rP7yVVy5qUc6mzqnbvvskmR4OvN.jpg", 
                top10: true, 
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 20,
                youtube: "https://www.youtube.com/watch?v=n5rh7O4IDc0" ,
                relevancia: 88,
                idade: "A14",
                duracao: "1h43",    
                tags: ["Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/7NUAiD9n6Cu6u5rzYLscMSPNYZC.jpg", 
                top10: true, 
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 59,
                youtube: "https://www.youtube.com/watch?v=mpgel-TjMKk" ,
                relevancia: 75,
                idade: "L",
                duracao: "1h38",    
                tags: ["Suspense", "Sobrenatural"]
            },
        ]
    },
    Alex: {
        "Assistindo": [
            { img: "https://image.tmdb.org/t/p/original/yjjObRZC5T38PhdUF8rt7ezNXgT.jpg", 
                top10: true, 
                badge: "Sci-fi", 
                badgeColor: "red", 
                progress: 10,
                relevancia: 92,
                idade: "A18",
                duracao: "2h33",    
                tags: ["Ação", "Guerra", "Drama"],
                youtube: "https://www.youtube.com/watch?v=sE8hc4gVyGo" 
            },

            { img: "https://imageio.forbes.com/specials-images/imageserve/5d1455be34a5c4000849a5a5/0x0.jpg?format=jpg&crop=1245,700,x155,y0,safe&height=900&width=1600&fit=bounds", 
                progress: 89, 
                relevancia: 84,
                idade: "A14",
                duracao: "2h10",    
                tags: ["Ação", "Ficção Científica", "Aventura"],
                youtube: "https://www.youtube.com/watch?v=Nt9L1jCKGnE"
            },

            { img: "https://image.tmdb.org/t/p/original/cQ6PAFAV33sj3slCpJe56z3jE70.jpg", 
                top10: true,
                badge: "Série", 
                badgeColor: "red", 
                progress: 45,
                youtube: "https://www.youtube.com/watch?v=drLzqW5WOI8" ,
                relevancia: 93,
                idade: "A16",
                duracao: "15 temporadas",    
                tags: ["Suspense", "Terror", "Drama"]
            },

            { img: "https://image.tmdb.org/t/p/original/qmsDsg7uAIHppsMXAChKDRFZwKL.jpg", 
                progress: 50,
                relevancia: 78,
                idade: "A12",
                duracao: "2h02",    
                tags: ["Ação", "Thriller"] ,
                youtube: "https://www.youtube.com/watch?v=wdok0rZdmx4" 
            },
        ],
        "Séries": [
            { img: "https://image.tmdb.org/t/p/original/cQ6PAFAV33sj3slCpJe56z3jE70.jpg", 
                top10: true,
                badge: "Série", 
                badgeColor: "red", 
                progress: 45,
                youtube: "https://www.youtube.com/watch?v=drLzqW5WOI8" ,
                relevancia: 93,
                idade: "A16",
                duracao: "15 temporadas",    
                tags: ["Suspense", "Terror", "Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/eBuykAJMJYhm7eloKsNsbaHoJU6.jpg",
                top10: true, 
                progress: 15,
                youtube: "https://www.youtube.com/watch?v=VxEEGi9V0kI" ,
                relevancia: 81,
                idade: "A16",
                duracao: "1 temporada",    
                tags: ["Terror", "Mistério", "Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/6QO6aDy0GCo2v3q1MAXgM5xNBu3.jpg",
                badge: "Novo episódio", 
                badgeColor: "red", 
                progress: 94,
                youtube: "https://www.youtube.com/watch?v=P_-r11fcDTc" ,
                relevancia: 95,
                idade: "A16",
                duracao: "6 temporadas",    
                tags: ["Ficção policial", "Drama", "Crime"]
            },
            { img: "https://image.tmdb.org/t/p/original/3fCETnALd7EBFccZlEDnheZxMQb.jpg", 
                badge: "Novidade", 
                badgeColor: "red", 
                youtube: "https://www.youtube.com/watch?v=B8qtYK9FzEc",
                relevancia: 92,
                idade: "A18",
                duracao: "8 temporadas",    
                tags: ["Drama", "Crime", "Mistério"]
            },
        ],
        "Filmes": [
            { img: "https://image.tmdb.org/t/p/original/v0v0hmAZuskaypC7GgfxPcFbs5L.jpg", 
                top10: true, 
                youtube: "www.youtube.com/watch?v=6iB21hsprAQ&pp=ygUZc2lsZW5jZSBvZiBsYW1icyB0cmFpbGVyIA%3D%3D" ,
                relevancia: 93,
                idade: "A16",
                duracao: "1h58",    
                tags: ["Thriller", "Crime", "Drama"]
            },
            { img: "https://image.tmdb.org/t/p/original/li14vFylchSu5zDPeeYycQyMltP.jpg", 
                top10: true, 
                badge: "Novidade", 
                badgeColor: "red", 
                youtube: "https://www.youtube.com/watch?v=C2NWGAqZhF4" ,
                relevancia: 83,
                idade: "A12",
                duracao: "2h05",    
                tags: ["Thriller", "Crime"]
            },
            { img: "https://image.tmdb.org/t/p/original/yjjObRZC5T38PhdUF8rt7ezNXgT.jpg", 
                top10: true, 
                badge: "Sci-fi", 
                badgeColor: "red", 
                progress: 10,
                relevancia: 92,
                idade: "A18",
                duracao: "2h33",    
                tags: ["Ação", "Guerra", "Drama"],
                youtube: "https://www.youtube.com/watch?v=sE8hc4gVyGo" 
            },
            { img: "https://image.tmdb.org/t/p/original/7rP0NnfBgzmLGrUOg4U1cY3IvZg.jpg", 
                top10: true, 
                badge: "Novo episódio", 
                badgeColor: "red", 
                youtube: "https://www.youtube.com/watch?v=DzfpyUB60YY" ,
                relevancia: 86,
                idade: "A14",
                duracao: "1h44",    
                tags: ["Terror", "Mistério", "Thriller"]
            },
        ]
    }
};
